-- ─── Create knowledge graph with AI Pipeline ─────────────────────
-- ---------------------------------------------------------------------------
-- Model Registration
-- ---------------------------------------------------------------------------
-- SELECT model_registry.model_remove('text-embedding-3-small');
SELECT model_registry.model_add(
    'default-chat',                                 -- a unique alias for your model
    'https://YOUR_RESOURCE.services.ai.azure.com/', -- your model endpoint URL
    'gpt-5.4',                       -- deployment name
    'gpt-5.4',                       -- model name
    NULL,                                           -- API version (NULL for latest)
    'subscription-key',                             -- auth type
    'YOUR_API_KEY'                                  -- endpoint key
);

-- ---------------------------------------------------------------------------
-- See Models
-- ---------------------------------------------------------------------------

SELECT * FROM model_registry.model_list_all();

-- ---------------------------------------------------------------------------
-- Create the pipeline sink table
-- The pipeline appends columns as each step runs:
--   ai.chunk    -> doc_id, chunk_index, chunk_text, metadata
--   ai.extract  -> merges the extracted style into metadata (e.g. {"style": "..."})
--   ai.generate -> generated_text (the complementary styles)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS style_tagger_output (
    id             INT GENERATED BY DEFAULT AS IDENTITY,
    doc_id         INT,
    chunk_index    INT,
    chunk_text     TEXT,
    generated_text TEXT,
    metadata       JSONB
);

-- ---------------------------------------------------------------------------
-- Create a pipeline to tag product styles
-- ---------------------------------------------------------------------------
SELECT ai.create_pipeline(
    name   => 'style_tagger',
    source => ai.table_source('product_sample'),
    steps  => ARRAY[
        ai.chunk(input => 'content'),
        ai.extract(
            model        => 'default-chat',
            input        => 'chunk_text',
            data         => ARRAY[
                                'style: string - the furniture design style, one of: Mid-Century Modern, Industrial, Scandinavian, Bohemian, Farmhouse, Minimalist'
            ]
        ),
        ai.generate(
            input         => 'chunk_text',
            system_prompt => 'Given this product, output ONLY a comma-separated list of 1-2 complementary furniture design styles from this list: Mid-Century Modern, Industrial, Scandinavian, Bohemian, Farmhouse, Minimalist. No explanation, just the style names.',
            model         => 'default-chat'
        )
    ],
    sink    => ai.table_sink('style_tagger_output'),
    trigger => 'on_change'
);

SELECT ai.run('style_tagger');
SELECT * FROM ai.status('style_tagger');



-- ─── Check: Flash style pipeline output (~1 min) ─────────────────────
-- Show 5 rows — this is what feeds the graph
SELECT doc_id, left(chunk_text, 60) AS product, metadata->'style' AS style, generated_text AS related_styles
FROM style_tagger_output LIMIT 5;

-- Verify style distribution
SELECT metadata->'style' AS style, COUNT(*) FROM style_tagger_output GROUP BY style ORDER BY count DESC;

----- Bonus Graphs ------
SET search_path = ag_catalog, "$user", public, pgfts;

-- Simple: "I picked this coffee table. What rugs, lamps, and chairs match its style?"
SELECT * FROM ag_catalog.cypher('style_graph', $$
    MATCH (seed:Product {id: 2315})-[edge1:HAS_STYLE]->(s:Style)<-[edge2:HAS_STYLE]-(recommendation:Product)
    MATCH (seed)-[edge3:IN_CATEGORY]->(seedCat:Category)
    MATCH (recommendation)-[edge4:IN_CATEGORY]->(recCat:Category)
    WHERE seedCat.name <> recCat.name
    RETURN seed, edge1, s, edge2, recommendation, edge3, seedCat, edge4, recCat
    LIMIT 10
$$) AS (seed agtype, edge1 agtype, style agtype, edge2 agtype, recommendation agtype, edge3 agtype, seedCat agtype, edge4 agtype, recCat agtype);


-- "Which styles bridge the most categories?"
SELECT * FROM ag_catalog.cypher('style_graph', $$
    MATCH (p:Product)-[edge1:HAS_STYLE]->(s:Style),
          (p)-[edge2:IN_CATEGORY]->(c:Category)
    RETURN p, edge1, s, edge2, c
$$) AS (p agtype, edge1 agtype, s agtype, edge2 agtype, c agtype);

