
-- ---------------------------------------------------------------------------
-- Sample Data
-- ---------------------------------------------------------------------------
SELECT * FROM product_sample LIMIT 5;

-- ---------------------------------------------------------------------------
-- Model Registration
-- ---------------------------------------------------------------------------
-- SELECT model_registry.model_remove('text-embedding-3-small');
SELECT model_registry.model_add(
    'text-embedding-3-small',                                 -- a unique alias for your model
    'https://YOUR_RESOURCE.services.ai.azure.com/', -- your model endpoint URL
    'text-embedding-3-small',                       -- deployment name
    'text-embedding-3-small',                       -- model name
    NULL,                                           -- API version (NULL for latest)
    'subscription-key',                             -- auth type
    'YOUR_API_KEY'                                  -- endpoint key
);

-- ---------------------------------------------------------------------------
-- See Models
-- ---------------------------------------------------------------------------

SELECT * FROM model_registry.model_list_all();

-- ---------------------------------------------------------------------------
-- Pipeline Creation
-- ---------------------------------------------------------------------------

-- DROP TABLE IF EXISTS embedding_pipeline_output;
CREATE TABLE IF NOT EXISTS embedding_pipeline_output (
    id          INT GENERATED BY DEFAULT AS IDENTITY,
    doc_id      INT,
    chunk_index INT,
    chunk_text  TEXT,
    embedding   vector(1536),
    metadata    JSONB
);

SELECT ai.create_pipeline(
    name    => 'embedding_pipeline',
    source  => ai.table_source('product_sample'),
    steps   => ARRAY[
        ai.chunk(input => 'content',
                 chunk_size => 1024, 
                 overlap => 128), -- generates chunk_text, chunk_index, etc.
        ai.embed(model => 'text-embedding-3-small', 
                 input => 'chunk_text',
                 dimensions => 1536,
                 batch_size => 20)
    ],
    sink    => ai.table_sink('embedding_pipeline_output'),
    trigger => 'on_change'
);
SELECT ai.run('embedding_pipeline');

-- SELECT ai.drop_pipeline('embedding_pipeline') 

-- ---------------------------------------------------------------------------
-- Monitor Pipeline 
-- ---------------------------------------------------------------------------

SELECT * FROM ai.status('embedding_pipeline');

-- ---------------------------------------------------------------------------
-- Look at output table
-- ---------------------------------------------------------------------------

SELECT count(*) FROM embedding_pipeline_output;
SELECT * FROM embedding_pipeline_output;

-- Semantic search against the catalog.
SELECT doc_id, chunk_text, chunk_index
     FROM embedding_pipeline_output
     ORDER BY embedding <=> azure_openai.create_embeddings(
                                'text-embedding-3-small',
                                'Best chair that is comfortable for a living room')::vector
     LIMIT 5;
    
-- ---------------------------------------------------------------------------
-- Auto-Embedding on New Rows
-- ---------------------------------------------------------------------------

INSERT INTO product_sample (title, content)
VALUES (
    'New Chair for Living Room',
    'A comfortable and stylish chair perfect for any living room setting. Features ergonomic design, high-quality materials, and a modern aesthetic that complements various interior styles.'
);

SELECT count(*) FROM embedding_pipeline_output;

SELECT *
     FROM embedding_pipeline_output
     ORDER BY embedding <=> azure_openai.create_embeddings(
                                'text-embedding-3-small',
                                'Best chair that is comfortable for a living room')::vector
     LIMIT 5;
